import axios from 'axios';

export function showBanner(payload) {
    return {
        type: 'SHOW_BANNER',
        payload
    };
}

export function hideBanner() {
    return {
        type: 'HIDE_BANNER'
    };
}

export function setProductPickerOpen(isOpen) {
    return {
        type: 'SET_PICKER_MODAL_STATE',
        payload: isOpen
    };
}

const addProducts = (products, pageNum, pageSize) =>
    axios.post(`/api/products?page=${pageNum}&limit=${pageSize}`, products);

export function productsAddedSuccess(products) {
    return {
        type: 'ADD_SELECTED_PRODUCTS',
        payload: products
    };
}

export function addSelectedProducts(products, pageNum, pageSize) {
    return dispatch =>
        addProducts(products, pageNum, pageSize)
        .then(data => dispatch(productsAddedSuccess(data)))
        .then(() => {
            const bannerOpts = {
                status: 'success',
                title: 'Products added',
                message: 'The products you selected are now enabled for viewing in AR'
            };
            return dispatch(showBanner(bannerOpts));
        })
        .catch((err) => {
            console.log(err);
            const bannerOpts = {
                status: 'critical',
                title: 'Products could not be added',
                message: 'There was a problem adding these products. Please try again'
            };
            return dispatch(showBanner(bannerOpts));
        });
}

export function onFiltersChange(filters) {
    return {
        type: 'SET_FILTERS',
        payload: filters
    };
}

export function getProducts(pageSize) {
    return {
        type: 'GET_PRODUCTS',
        payload: axios.get(`/api/products?limit=${pageSize}`)
    };
}

export function handlePagination(direction, pageNum, pageSize) {
    const next = direction === 'next'; // direction is 'next' or 'prev'
    return {
        type: next ? 'NEXT_PAGE' : 'PREV_PAGE',
        payload: axios.get(`/api/products?page=${next ? pageNum+1 : Math.max(pageNum-1, 0)}&limit=${pageSize}`)
    }
}

export function setDeleteAlertOpen(opts) {
    return {
        type: 'OPEN_DELETE_ALERT',
        payload: opts
    };
}

const deleteProduct = (id, pageNum, pageSize) =>
    axios.delete(`/api/products/${id}?page=${pageNum}&limit=${pageSize}`);

export function updateProductsAfterDelete(payload) {
    return {
        type: 'DELETE_PRODUCT',
        payload
    }
}

export function deleteProductAndCloseModal(id, pageNum, pageSize) {
    return dispatch =>
        deleteProduct(id, pageNum, pageSize)
        .then(({ data }) => {
            console.log('data!!!!!!!!!!', data);
            return data.products.length ?
                { payload: { data } } :
                dispatch(handlePagination('prev', pageNum, pageSize));
        })
        .then(({ payload }) => {
            return dispatch(updateProductsAfterDelete(payload))
        })
        .then(() => dispatch(setDeleteAlertOpen({ isOpen: false, id: 0, title: '' })))
        .then(() => {
            const bannerOpts = {
                status: 'success',
                title: 'Delete Successful',
                message: 'Product Successfully deleted'
            };
            return dispatch(showBanner(bannerOpts));
        })
        .catch((err) => {
            console.log(err);
            const bannerOpts = {
                status: 'critical',
                title: 'Delete Failure',
                message: 'There was a problem deleting this product. Please try again'
            };
            return dispatch(showBanner(bannerOpts));
        });
}

export function updateProductAfterSaveEditForm(id, payload) {
    return {
        type: 'EDIT_FORM_SAVE',
        id,
        payload
    };
}

const updateProduct = (id, payload) => {
    // this will allow axios to recognize form generated by redux-form as a multipart form,
    // which is needed because this form contains a file
    const body = new FormData();
    Object.keys(payload).forEach(key => body.append(key, payload[key]));
    return axios.patch(`/api/products/${id}`, body);
};

export function saveEditForm(productId, payload) {
    return dispatch =>
        updateProduct(productId, payload)
        .then((payload) => dispatch(updateProductAfterSaveEditForm(productId, payload)))
        .then(() => {
            const bannerOpts = {
                status: 'success',
                title: 'Updated successful',
                message: 'Product Successfully updated'
            };
            return dispatch(showBanner(bannerOpts));
        })
        .catch((err) => {
            console.log(err);
            const bannerOpts = {
                status: 'critical',
                title: 'Update Failure',
                message: 'There was a problem updating this product. Please try again'
            };
            return dispatch(showBanner(bannerOpts));
        });
}